import fs from 'node:fs/promises';
import path from 'node:path';
import { currentTaskPath } from './current-task.js';
import { readUpstreamHookMetadata, type UpstreamHookMetadata } from './hook-shadow.js';
import { isPathInside } from './paths.js';
import type { CurrentTask } from './types.js';

export type HookInstallTarget = 'codex' | 'ccpanes' | 'both';
export type HookInstallSurface = 'codex' | 'ccpanes';

export interface ProposedConfigChange {
  surface: HookInstallSurface;
  configPath: string;
  action: 'review_patch_only';
  patchCandidate: string;
  notes: string;
}

export interface HookInstallPlan {
  schema: 'ccpanes.hook-install-plan.v1';
  mode: 'review-only';
  createdAt: string;
  target: HookInstallTarget;
  taskId: string;
  prototypeRoot: string;
  upstreamHook: UpstreamHookMetadata;
  shadowCommand: string;
  proposedConfigChanges: ProposedConfigChange[];
  manualChecks: string[];
}

export interface CreateHookInstallPlanInput {
  task: CurrentTask;
  prototypeRoot: string;
  target: HookInstallTarget;
  upstreamHookPath: string;
  now?: string;
}

const forbiddenPlanOutRoots = [
  'C:/Users/AI001/.codex',
  'C:/Users/AI001/.claude',
  'C:/Users/AI001/.cc-panes',
  'D:/cc-pane/tool/repos/comet',
  'D:/cc-pane/tool/repos/fastctx'
];

const configPaths: Record<HookInstallSurface, string> = {
  codex: 'C:/Users/AI001/.codex/config.toml',
  ccpanes: 'C:/Users/AI001/.cc-panes/config.toml'
};

function surfacesForTarget(target: HookInstallTarget): HookInstallSurface[] {
  if (target === 'codex') return ['codex'];
  if (target === 'ccpanes') return ['ccpanes'];
  if (target === 'both') return ['codex', 'ccpanes'];
  throw new Error(`invalid hook install target: ${target}`);
}

function quote(value: string): string {
  return `"${value.replace(/"/g, '\\"')}"`;
}

function makeShadowCommand(input: CreateHookInstallPlanInput): string {
  const cliPath = path.join(input.prototypeRoot, 'dist', 'src', 'cli.js').replace(/\\/g, '/');
  const auditPath = path.join(input.task.worktreeRoot, '.ccpanes-task', 'shadow-audit.json').replace(/\\/g, '/');
  return [
    'node',
    quote(cliPath),
    'hook-shadow',
    '--task',
    quote(currentTaskPath(input.task.worktreeRoot).replace(/\\/g, '/')),
    '--upstream-hook',
    quote(input.upstreamHookPath.replace(/\\/g, '/')),
    '--out',
    quote(auditPath)
  ].join(' ');
}

function makePatchCandidate(surface: HookInstallSurface, shadowCommand: string): string {
  return [
    `# ${surface} hook integration candidate`,
    '# review-only patch candidate generated by ccpanes-task-probe',
    '# expected behavior: pipe hook event JSON to the shadow command first',
    '[hooks.pre_tool_use]',
    `command = ${JSON.stringify(shadowCommand)}`,
    'mode = "shadow"',
    ''
  ].join('\n');
}

export async function createHookInstallPlan(input: CreateHookInstallPlanInput): Promise<HookInstallPlan> {
  const upstreamHook = await readUpstreamHookMetadata(input.upstreamHookPath);
  if (!upstreamHook) throw new Error('missing upstream hook path');
  const shadowCommand = makeShadowCommand(input);
  const proposedConfigChanges = surfacesForTarget(input.target).map((surface) => ({
    surface,
    configPath: configPaths[surface],
    action: 'review_patch_only' as const,
    patchCandidate: makePatchCandidate(surface, shadowCommand),
    notes: 'Patch candidate only; review and apply manually after shadow audit passes.'
  }));
  return {
    schema: 'ccpanes.hook-install-plan.v1',
    mode: 'review-only',
    createdAt: input.now ?? new Date().toISOString(),
    target: input.target,
    taskId: input.task.taskId,
    prototypeRoot: input.prototypeRoot,
    upstreamHook,
    shadowCommand,
    proposedConfigChanges,
    manualChecks: [
      'Run npm test, npm run typecheck, npm run build, npm run smoke in the prototype root.',
      'Run hook-shadow with a synthetic event and inspect ccpanes.hook-shadow-audit.v1.',
      'Confirm upstreamHook.sha256 matches the expected skills-hub-hook.exe hash.',
      'Review proposed config patch text before any user config write.'
    ]
  };
}

function assertSafePlanOutPath(outPath: string): void {
  for (const root of forbiddenPlanOutRoots) {
    if (isPathInside(root, outPath)) {
      throw new Error(`invalid hook install plan output path: forbidden root ${root}`);
    }
  }
}

export async function writeHookInstallPlanAtomic(outPath: string, plan: HookInstallPlan): Promise<void> {
  assertSafePlanOutPath(outPath);
  const dir = path.dirname(outPath);
  await fs.mkdir(dir, { recursive: true });
  const tempPath = path.join(dir, `${path.basename(outPath)}.${process.pid}.${Date.now()}.tmp`);
  await fs.writeFile(tempPath, `${JSON.stringify(plan, null, 2)}\n`, 'utf8');
  await fs.rename(tempPath, outPath);
}
